//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_performance_track
    {
        public hrm_performance_track()
        {
            this.hrm_performance_tracker_log = new HashSet<hrm_performance_tracker_log>();
            this.hrm_performance_tracker_reviewer = new HashSet<hrm_performance_tracker_reviewer>();
        }
    
        public int id { get; set; }
        public int emp_number { get; set; }
        public string tracker_name { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public Nullable<int> added_by { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual hs_hr_employee hs_hr_employee1 { get; set; }
        public virtual ICollection<hrm_performance_tracker_log> hrm_performance_tracker_log { get; set; }
        public virtual ICollection<hrm_performance_tracker_reviewer> hrm_performance_tracker_reviewer { get; set; }
    }
}
