//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_leave_entitlement
    {
        public int id { get; set; }
        public int leave_id { get; set; }
        public long entitlement_id { get; set; }
    
        public virtual hrm_leave hrm_leave { get; set; }
        public virtual hrm_leave_entitlement hrm_leave_entitlement { get; set; }
    }
}
