//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_work_week
    {
        public long id { get; set; }
        public Nullable<long> operational_country_id { get; set; }
        public byte mon { get; set; }
        public byte tue { get; set; }
        public byte wed { get; set; }
        public byte thu { get; set; }
        public byte fri { get; set; }
        public byte sat { get; set; }
        public byte sun { get; set; }
    
        public virtual hrm_operational_country hrm_operational_country { get; set; }
    }
}
