//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_reviewer_rating
    {
        public int id { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<int> kpi_id { get; set; }
        public Nullable<int> review_id { get; set; }
        public int reviewer_id { get; set; }
        public string comment { get; set; }
    
        public virtual hrm_performance_review hrm_performance_review { get; set; }
        public virtual hrm_reviewer hrm_reviewer { get; set; }
    }
}
