//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_timesheet_item
    {
        public long timesheet_item_id { get; set; }
        public long timesheet_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<long> duration { get; set; }
        public string comment { get; set; }
        public long project_id { get; set; }
        public long employee_id { get; set; }
        public long activity_id { get; set; }
    }
}
