//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_operational_country
    {
        public hrm_operational_country()
        {
            this.hrm_holiday = new HashSet<hrm_holiday>();
            this.hrm_leave_type = new HashSet<hrm_leave_type>();
            this.hrm_work_week = new HashSet<hrm_work_week>();
        }
    
        public long id { get; set; }
        public string country_code { get; set; }
    
        public virtual ICollection<hrm_holiday> hrm_holiday { get; set; }
        public virtual ICollection<hrm_leave_type> hrm_leave_type { get; set; }
        public virtual hs_hr_country hs_hr_country { get; set; }
        public virtual ICollection<hrm_work_week> hrm_work_week { get; set; }
    }
}
