//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_screen
    {
        public hrm_screen()
        {
            this.hrm_data_group_screen = new HashSet<hrm_data_group_screen>();
            this.hrm_menu_item = new HashSet<hrm_menu_item>();
            this.hrm_user_role_screen = new HashSet<hrm_user_role_screen>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int module_id { get; set; }
        public string action_url { get; set; }
    
        public virtual ICollection<hrm_data_group_screen> hrm_data_group_screen { get; set; }
        public virtual ICollection<hrm_menu_item> hrm_menu_item { get; set; }
        public virtual hrm_module hrm_module { get; set; }
        public virtual ICollection<hrm_user_role_screen> hrm_user_role_screen { get; set; }
    }
}
