//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_location
    {
        public hrm_location()
        {
            this.hs_hr_employee = new HashSet<hs_hr_employee>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string country_code { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string zip_code { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string notes { get; set; }
    
        public virtual hs_hr_country hs_hr_country { get; set; }
        public virtual ICollection<hs_hr_employee> hs_hr_employee { get; set; }
    }
}
