//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_data_group_screen
    {
        public int id { get; set; }
        public Nullable<int> data_group_id { get; set; }
        public Nullable<int> screen_id { get; set; }
        public Nullable<int> permission { get; set; }
    
        public virtual hrm_data_group hrm_data_group { get; set; }
        public virtual hrm_screen hrm_screen { get; set; }
    }
}
