//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_job_vacancy
    {
        public hrm_job_vacancy()
        {
            this.hrm_job_candidate_history = new HashSet<hrm_job_candidate_history>();
            this.hrm_job_candidate_vacancy = new HashSet<hrm_job_candidate_vacancy>();
            this.hrm_job_vacancy_attachment = new HashSet<hrm_job_vacancy_attachment>();
        }
    
        public int id { get; set; }
        public int job_title_code { get; set; }
        public Nullable<int> hiring_manager_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> no_of_positions { get; set; }
        public int status { get; set; }
        public bool published_in_feed { get; set; }
        public System.DateTime defined_time { get; set; }
        public System.DateTime updated_time { get; set; }
    
        public virtual ICollection<hrm_job_candidate_history> hrm_job_candidate_history { get; set; }
        public virtual ICollection<hrm_job_candidate_vacancy> hrm_job_candidate_vacancy { get; set; }
        public virtual hrm_job_title hrm_job_title { get; set; }
        public virtual ICollection<hrm_job_vacancy_attachment> hrm_job_vacancy_attachment { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
