//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_display_field_group
    {
        public hrm_display_field_group()
        {
            this.hrm_composite_display_field = new HashSet<hrm_composite_display_field>();
            this.hrm_display_field = new HashSet<hrm_display_field>();
            this.hrm_selected_display_field_group = new HashSet<hrm_selected_display_field_group>();
            this.hrm_summary_display_field = new HashSet<hrm_summary_display_field>();
        }
    
        public long id { get; set; }
        public long report_group_id { get; set; }
        public string name { get; set; }
        public bool is_list { get; set; }
    
        public virtual ICollection<hrm_composite_display_field> hrm_composite_display_field { get; set; }
        public virtual ICollection<hrm_display_field> hrm_display_field { get; set; }
        public virtual hrm_report_group hrm_report_group { get; set; }
        public virtual ICollection<hrm_selected_display_field_group> hrm_selected_display_field_group { get; set; }
        public virtual ICollection<hrm_summary_display_field> hrm_summary_display_field { get; set; }
    }
}
