//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_available_group_field
    {
        public long report_group_id { get; set; }
        public long group_field_id { get; set; }
    
        public virtual hrm_group_field hrm_group_field { get; set; }
    }
}
