//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_login
    {
        public int id { get; set; }
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string user_role_name { get; set; }
        public bool user_role_predefined { get; set; }
        public System.DateTime login_time { get; set; }
    }
}
