//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_email_configuration
    {
        public int id { get; set; }
        public string mail_type { get; set; }
        public string sent_as { get; set; }
        public string sendmail_path { get; set; }
        public string smtp_host { get; set; }
        public Nullable<int> smtp_port { get; set; }
        public string smtp_username { get; set; }
        public string smtp_password { get; set; }
        public string smtp_auth_type { get; set; }
        public string smtp_security_type { get; set; }
    }
}
