//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_job_candidate_vacancy
    {
        public Nullable<int> id { get; set; }
        public int candidate_id { get; set; }
        public int vacancy_id { get; set; }
        public string status { get; set; }
        public System.DateTime applied_date { get; set; }
    
        public virtual hrm_job_candidate hrm_job_candidate { get; set; }
        public virtual hrm_job_vacancy hrm_job_vacancy { get; set; }
    }
}
