//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_type
    {
        public hrm_leave_type()
        {
            this.hrm_leave = new HashSet<hrm_leave>();
            this.hrm_leave_adjustment = new HashSet<hrm_leave_adjustment>();
            this.hrm_leave_entitlement = new HashSet<hrm_leave_entitlement>();
            this.hrm_leave_request = new HashSet<hrm_leave_request>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public bool deleted { get; set; }
        public bool exclude_in_reports_if_no_entitlement { get; set; }
        public Nullable<long> operational_country_id { get; set; }
    
        public virtual ICollection<hrm_leave> hrm_leave { get; set; }
        public virtual ICollection<hrm_leave_adjustment> hrm_leave_adjustment { get; set; }
        public virtual ICollection<hrm_leave_entitlement> hrm_leave_entitlement { get; set; }
        public virtual ICollection<hrm_leave_request> hrm_leave_request { get; set; }
        public virtual hrm_operational_country hrm_operational_country { get; set; }
    }
}
