//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_group_field
    {
        public hrm_group_field()
        {
            this.hrm_available_group_field = new HashSet<hrm_available_group_field>();
            this.hrm_selected_group_field = new HashSet<hrm_selected_group_field>();
        }
    
        public long group_field_id { get; set; }
        public string name { get; set; }
        public string group_by_clause { get; set; }
        public string group_field_widget { get; set; }
    
        public virtual ICollection<hrm_available_group_field> hrm_available_group_field { get; set; }
        public virtual ICollection<hrm_selected_group_field> hrm_selected_group_field { get; set; }
    }
}
