//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_workflow_state_machine
    {
        public long id { get; set; }
        public string workflow { get; set; }
        public string state { get; set; }
        public string role { get; set; }
        public string action { get; set; }
        public string resulting_state { get; set; }
        public string roles_to_notify { get; set; }
        public int priority { get; set; }
    }
}
