//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_menu_item
    {
        public int id { get; set; }
        public string menu_title { get; set; }
        public Nullable<int> screen_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public sbyte level { get; set; }
        public int order_hint { get; set; }
        public string url_extras { get; set; }
        public sbyte status { get; set; }
    
        public virtual hrm_screen hrm_screen { get; set; }
    }
}
