//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_emp_termination
    {
        public hrm_emp_termination()
        {
            this.hs_hr_employee1 = new HashSet<hs_hr_employee>();
        }
    
        public int id { get; set; }
        public Nullable<int> emp_number { get; set; }
        public Nullable<int> reason_id { get; set; }
        public System.DateTime termination_date { get; set; }
        public string note { get; set; }
    
        public virtual hrm_emp_termination_reason hrm_emp_termination_reason { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual ICollection<hs_hr_employee> hs_hr_employee1 { get; set; }
    }
}
