//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_emp_license
    {
        public int emp_number { get; set; }
        public int license_id { get; set; }
        public string license_no { get; set; }
        public Nullable<System.DateTime> license_issued_date { get; set; }
        public Nullable<System.DateTime> license_expiry_date { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual hrm_license hrm_license { get; set; }
    }
}
