//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_organization_gen_info
    {
        public int id { get; set; }
        public string name { get; set; }
        public string tax_id { get; set; }
        public string registration_number { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string zip_code { get; set; }
        public string street1 { get; set; }
        public string street2 { get; set; }
        public string note { get; set; }
    }
}
