//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_emp_education
    {
        public int id { get; set; }
        public int emp_number { get; set; }
        public int education_id { get; set; }
        public string institute { get; set; }
        public string major { get; set; }
        public Nullable<decimal> year { get; set; }
        public string score { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual hrm_education hrm_education { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
