//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_user
    {
        public hrm_user()
        {
            this.hrm_leave_adjustment = new HashSet<hrm_leave_adjustment>();
            this.hrm_leave_comment = new HashSet<hrm_leave_comment>();
            this.hrm_leave_entitlement = new HashSet<hrm_leave_entitlement>();
            this.hrm_leave_request_comment = new HashSet<hrm_leave_request_comment>();
            this.hrm_performance_tracker_log = new HashSet<hrm_performance_tracker_log>();
            this.hrm_timesheet_action_log = new HashSet<hrm_timesheet_action_log>();
            this.hs_hr_mailnotifications = new HashSet<hs_hr_mailnotifications>();
        }
    
        public int id { get; set; }
        public int user_role_id { get; set; }
        public Nullable<int> emp_number { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public bool deleted { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> modified_user_id { get; set; }
        public Nullable<int> created_by { get; set; }
    
        public virtual ICollection<hrm_leave_adjustment> hrm_leave_adjustment { get; set; }
        public virtual ICollection<hrm_leave_comment> hrm_leave_comment { get; set; }
        public virtual ICollection<hrm_leave_entitlement> hrm_leave_entitlement { get; set; }
        public virtual ICollection<hrm_leave_request_comment> hrm_leave_request_comment { get; set; }
        public virtual ICollection<hrm_performance_tracker_log> hrm_performance_tracker_log { get; set; }
        public virtual ICollection<hrm_timesheet_action_log> hrm_timesheet_action_log { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual hrm_user_role hrm_user_role { get; set; }
        public virtual ICollection<hs_hr_mailnotifications> hs_hr_mailnotifications { get; set; }
    }
}
