//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_reviewer
    {
        public hrm_reviewer()
        {
            this.hrm_reviewer_rating = new HashSet<hrm_reviewer_rating>();
        }
    
        public int id { get; set; }
        public Nullable<int> review_id { get; set; }
        public Nullable<int> employee_number { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> reviewer_group_id { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public string comment { get; set; }
    
        public virtual hrm_performance_review hrm_performance_review { get; set; }
        public virtual ICollection<hrm_reviewer_rating> hrm_reviewer_rating { get; set; }
    }
}
