//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_filter_field
    {
        public hrm_filter_field()
        {
            this.hrm_selected_filter_field = new HashSet<hrm_selected_filter_field>();
        }
    
        public long filter_field_id { get; set; }
        public long report_group_id { get; set; }
        public string name { get; set; }
        public string where_clause_part { get; set; }
        public string filter_field_widget { get; set; }
        public int condition_no { get; set; }
        public string required { get; set; }
    
        public virtual hrm_report_group hrm_report_group { get; set; }
        public virtual ICollection<hrm_selected_filter_field> hrm_selected_filter_field { get; set; }
    }
}
