//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_report
    {
        public hrm_report()
        {
            this.hrm_selected_composite_display_field = new HashSet<hrm_selected_composite_display_field>();
            this.hrm_selected_display_field_group = new HashSet<hrm_selected_display_field_group>();
            this.hrm_selected_display_field = new HashSet<hrm_selected_display_field>();
            this.hrm_selected_filter_field = new HashSet<hrm_selected_filter_field>();
            this.hrm_selected_group_field = new HashSet<hrm_selected_group_field>();
        }
    
        public long report_id { get; set; }
        public string name { get; set; }
        public long report_group_id { get; set; }
        public bool use_filter_field { get; set; }
        public string type { get; set; }
    
        public virtual hrm_report_group hrm_report_group { get; set; }
        public virtual ICollection<hrm_selected_composite_display_field> hrm_selected_composite_display_field { get; set; }
        public virtual ICollection<hrm_selected_display_field_group> hrm_selected_display_field_group { get; set; }
        public virtual ICollection<hrm_selected_display_field> hrm_selected_display_field { get; set; }
        public virtual ICollection<hrm_selected_filter_field> hrm_selected_filter_field { get; set; }
        public virtual ICollection<hrm_selected_group_field> hrm_selected_group_field { get; set; }
    }
}
