//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_entitlement_type
    {
        public hrm_leave_entitlement_type()
        {
            this.hrm_leave_adjustment = new HashSet<hrm_leave_adjustment>();
            this.hrm_leave_entitlement = new HashSet<hrm_leave_entitlement>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public bool is_editable { get; set; }
    
        public virtual ICollection<hrm_leave_adjustment> hrm_leave_adjustment { get; set; }
        public virtual ICollection<hrm_leave_entitlement> hrm_leave_entitlement { get; set; }
    }
}
