//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_user_role_screen
    {
        public int id { get; set; }
        public int user_role_id { get; set; }
        public int screen_id { get; set; }
        public bool can_read { get; set; }
        public bool can_create { get; set; }
        public bool can_update { get; set; }
        public bool can_delete { get; set; }
    
        public virtual hrm_screen hrm_screen { get; set; }
        public virtual hrm_user_role hrm_user_role { get; set; }
    }
}
