//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_selected_filter_field
    {
        public long report_id { get; set; }
        public long filter_field_id { get; set; }
        public long filter_field_order { get; set; }
        public string value1 { get; set; }
        public string value2 { get; set; }
        public string where_condition { get; set; }
        public string type { get; set; }
    
        public virtual hrm_filter_field hrm_filter_field { get; set; }
        public virtual hrm_report hrm_report { get; set; }
    }
}
