//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_pay_grade
    {
        public hrm_pay_grade()
        {
            this.hrm_pay_grade_currency = new HashSet<hrm_pay_grade_currency>();
            this.hs_hr_emp_basicsalary = new HashSet<hs_hr_emp_basicsalary>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<hrm_pay_grade_currency> hrm_pay_grade_currency { get; set; }
        public virtual ICollection<hs_hr_emp_basicsalary> hs_hr_emp_basicsalary { get; set; }
    }
}
