//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_email_processor
    {
        public int id { get; set; }
        public int email_id { get; set; }
        public string class_name { get; set; }
    
        public virtual hrm_email hrm_email { get; set; }
    }
}
