//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_request
    {
        public hrm_leave_request()
        {
            this.hrm_leave = new HashSet<hrm_leave>();
            this.hrm_leave_request_comment = new HashSet<hrm_leave_request_comment>();
        }
    
        public long id { get; set; }
        public long leave_type_id { get; set; }
        public System.DateTime date_applied { get; set; }
        public int emp_number { get; set; }
        public string comments { get; set; }
    
        public virtual ICollection<hrm_leave> hrm_leave { get; set; }
        public virtual ICollection<hrm_leave_request_comment> hrm_leave_request_comment { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual hrm_leave_type hrm_leave_type { get; set; }
    }
}
