//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_job_candidate
    {
        public hrm_job_candidate()
        {
            this.hrm_job_candidate_attachment = new HashSet<hrm_job_candidate_attachment>();
            this.hrm_job_candidate_history = new HashSet<hrm_job_candidate_history>();
            this.hrm_job_candidate_vacancy = new HashSet<hrm_job_candidate_vacancy>();
            this.hrm_job_interview = new HashSet<hrm_job_interview>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string contact_number { get; set; }
        public int status { get; set; }
        public string comment { get; set; }
        public int mode_of_application { get; set; }
        public System.DateTime date_of_application { get; set; }
        public Nullable<int> cv_file_id { get; set; }
        public string cv_text_version { get; set; }
        public string keywords { get; set; }
        public Nullable<int> added_person { get; set; }
    
        public virtual ICollection<hrm_job_candidate_attachment> hrm_job_candidate_attachment { get; set; }
        public virtual ICollection<hrm_job_candidate_history> hrm_job_candidate_history { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
        public virtual ICollection<hrm_job_candidate_vacancy> hrm_job_candidate_vacancy { get; set; }
        public virtual ICollection<hrm_job_interview> hrm_job_interview { get; set; }
    }
}
