//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_data_group
    {
        public hrm_data_group()
        {
            this.hrm_data_group_screen = new HashSet<hrm_data_group_screen>();
            this.hrm_user_role_data_group = new HashSet<hrm_user_role_data_group>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> can_read { get; set; }
        public Nullable<sbyte> can_create { get; set; }
        public Nullable<sbyte> can_update { get; set; }
        public Nullable<sbyte> can_delete { get; set; }
    
        public virtual ICollection<hrm_data_group_screen> hrm_data_group_screen { get; set; }
        public virtual ICollection<hrm_user_role_data_group> hrm_user_role_data_group { get; set; }
    }
}
