//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_job_candidate_attachment
    {
        public int id { get; set; }
        public int candidate_id { get; set; }
        public string file_name { get; set; }
        public string file_type { get; set; }
        public int file_size { get; set; }
        public byte[] file_content { get; set; }
        public Nullable<int> attachment_type { get; set; }
    
        public virtual hrm_job_candidate hrm_job_candidate { get; set; }
    }
}
