//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_emp_reporting_method
    {
        public hrm_emp_reporting_method()
        {
            this.hs_hr_emp_reportto = new HashSet<hs_hr_emp_reportto>();
        }
    
        public int reporting_method_id { get; set; }
        public string reporting_method_name { get; set; }
    
        public virtual ICollection<hs_hr_emp_reportto> hs_hr_emp_reportto { get; set; }
    }
}
