//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_timesheet_action_log
    {
        public long timesheet_action_log_id { get; set; }
        public string comment { get; set; }
        public string action { get; set; }
        public System.DateTime date_time { get; set; }
        public int performed_by { get; set; }
        public long timesheet_id { get; set; }
    
        public virtual hrm_user hrm_user { get; set; }
    }
}
