//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_report_group
    {
        public hrm_report_group()
        {
            this.hrm_composite_display_field = new HashSet<hrm_composite_display_field>();
            this.hrm_display_field = new HashSet<hrm_display_field>();
            this.hrm_display_field_group = new HashSet<hrm_display_field_group>();
            this.hrm_filter_field = new HashSet<hrm_filter_field>();
            this.hrm_report = new HashSet<hrm_report>();
        }
    
        public long report_group_id { get; set; }
        public string name { get; set; }
        public string core_sql { get; set; }
    
        public virtual ICollection<hrm_composite_display_field> hrm_composite_display_field { get; set; }
        public virtual ICollection<hrm_display_field> hrm_display_field { get; set; }
        public virtual ICollection<hrm_display_field_group> hrm_display_field_group { get; set; }
        public virtual ICollection<hrm_filter_field> hrm_filter_field { get; set; }
        public virtual ICollection<hrm_report> hrm_report { get; set; }
    }
}
