//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave_comment
    {
        public int id { get; set; }
        public int leave_id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by_name { get; set; }
        public Nullable<int> created_by_id { get; set; }
        public Nullable<int> created_by_emp_number { get; set; }
        public string comments { get; set; }
    
        public virtual hrm_leave hrm_leave { get; set; }
        public virtual hrm_user hrm_user { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
