//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_license
    {
        public hrm_license()
        {
            this.hrm_emp_license = new HashSet<hrm_emp_license>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<hrm_emp_license> hrm_emp_license { get; set; }
    }
}
