//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_leave
    {
        public hrm_leave()
        {
            this.hrm_leave_comment = new HashSet<hrm_leave_comment>();
            this.hrm_leave_leave_entitlement = new HashSet<hrm_leave_leave_entitlement>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<short> status { get; set; }
        public string comments { get; set; }
        public long leave_request_id { get; set; }
        public long leave_type_id { get; set; }
        public int emp_number { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public sbyte duration_type { get; set; }
    
        public virtual ICollection<hrm_leave_comment> hrm_leave_comment { get; set; }
        public virtual hrm_leave_request hrm_leave_request { get; set; }
        public virtual hrm_leave_type hrm_leave_type { get; set; }
        public virtual ICollection<hrm_leave_leave_entitlement> hrm_leave_leave_entitlement { get; set; }
    }
}
