//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_job_title
    {
        public hrm_job_title()
        {
            this.hrm_job_specification_attachment = new HashSet<hrm_job_specification_attachment>();
            this.hrm_job_vacancy = new HashSet<hrm_job_vacancy>();
            this.hs_hr_employee = new HashSet<hs_hr_employee>();
            this.hrm_employment_status = new HashSet<hrm_employment_status>();
        }
    
        public int id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public string note { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    
        public virtual ICollection<hrm_job_specification_attachment> hrm_job_specification_attachment { get; set; }
        public virtual ICollection<hrm_job_vacancy> hrm_job_vacancy { get; set; }
        public virtual ICollection<hs_hr_employee> hs_hr_employee { get; set; }
        public virtual ICollection<hrm_employment_status> hrm_employment_status { get; set; }
    }
}
