//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hrm_holiday
    {
        public long id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<byte> recurring { get; set; }
        public Nullable<long> length { get; set; }
        public Nullable<long> operational_country_id { get; set; }
    
        public virtual hrm_operational_country hrm_operational_country { get; set; }
    }
}
