//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_emergency_contacts
    {
        public int emp_number { get; set; }
        public decimal eec_seqno { get; set; }
        public string eec_name { get; set; }
        public string eec_relationship { get; set; }
        public string eec_home_no { get; set; }
        public string eec_mobile_no { get; set; }
        public string eec_office_no { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
