//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_custom_fields
    {
        public int field_num { get; set; }
        public string name { get; set; }
        public int type { get; set; }
        public string screen { get; set; }
        public string extra_data { get; set; }
    }
}
