//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_attachment
    {
        public int emp_number { get; set; }
        public int eattach_id { get; set; }
        public string eattach_desc { get; set; }
        public string eattach_filename { get; set; }
        public Nullable<int> eattach_size { get; set; }
        public byte[] eattach_attachment { get; set; }
        public string eattach_type { get; set; }
        public string screen { get; set; }
        public Nullable<int> attached_by { get; set; }
        public string attached_by_name { get; set; }
        public System.DateTime attached_time { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
