//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_contract_extend
    {
        public int emp_number { get; set; }
        public decimal econ_extend_id { get; set; }
        public Nullable<System.DateTime> econ_extend_start_date { get; set; }
        public Nullable<System.DateTime> econ_extend_end_date { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
