//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_country
    {
        public hs_hr_country()
        {
            this.hrm_location = new HashSet<hrm_location>();
            this.hrm_operational_country = new HashSet<hrm_operational_country>();
        }
    
        public string cou_code { get; set; }
        public string name { get; set; }
        public string cou_name { get; set; }
        public string iso3 { get; set; }
        public Nullable<short> numcode { get; set; }
    
        public virtual ICollection<hrm_location> hrm_location { get; set; }
        public virtual ICollection<hrm_operational_country> hrm_operational_country { get; set; }
    }
}
