//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_employee
    {
        public hs_hr_employee()
        {
            this.hrm_emp_education = new HashSet<hrm_emp_education>();
            this.hrm_emp_license = new HashSet<hrm_emp_license>();
            this.hrm_emp_termination = new HashSet<hrm_emp_termination>();
            this.hrm_job_candidate = new HashSet<hrm_job_candidate>();
            this.hrm_job_candidate_history = new HashSet<hrm_job_candidate_history>();
            this.hrm_job_vacancy = new HashSet<hrm_job_vacancy>();
            this.hrm_leave_adjustment = new HashSet<hrm_leave_adjustment>();
            this.hrm_leave_comment = new HashSet<hrm_leave_comment>();
            this.hrm_leave_entitlement = new HashSet<hrm_leave_entitlement>();
            this.hrm_leave_request = new HashSet<hrm_leave_request>();
            this.hrm_leave_request_comment = new HashSet<hrm_leave_request_comment>();
            this.hrm_performance_review = new HashSet<hrm_performance_review>();
            this.hrm_performance_track = new HashSet<hrm_performance_track>();
            this.hrm_performance_track1 = new HashSet<hrm_performance_track>();
            this.hrm_performance_tracker_log = new HashSet<hrm_performance_tracker_log>();
            this.hrm_performance_tracker_reviewer = new HashSet<hrm_performance_tracker_reviewer>();
            this.hrm_project_admin = new HashSet<hrm_project_admin>();
            this.hrm_user = new HashSet<hrm_user>();
            this.hs_hr_emp_attachment = new HashSet<hs_hr_emp_attachment>();
            this.hs_hr_emp_basicsalary = new HashSet<hs_hr_emp_basicsalary>();
            this.hs_hr_emp_children = new HashSet<hs_hr_emp_children>();
            this.hs_hr_emp_contract_extend = new HashSet<hs_hr_emp_contract_extend>();
            this.hs_hr_emp_dependents = new HashSet<hs_hr_emp_dependents>();
            this.hs_hr_emp_emergency_contacts = new HashSet<hs_hr_emp_emergency_contacts>();
            this.hs_hr_emp_history_of_ealier_pos = new HashSet<hs_hr_emp_history_of_ealier_pos>();
            this.hs_hr_emp_language = new HashSet<hs_hr_emp_language>();
            this.hs_hr_emp_member_detail = new HashSet<hs_hr_emp_member_detail>();
            this.hs_hr_emp_passport = new HashSet<hs_hr_emp_passport>();
            this.hs_hr_emp_reportto = new HashSet<hs_hr_emp_reportto>();
            this.hs_hr_emp_reportto1 = new HashSet<hs_hr_emp_reportto>();
            this.hs_hr_emp_work_experience = new HashSet<hs_hr_emp_work_experience>();
            this.hs_hr_emp_skill = new HashSet<hs_hr_emp_skill>();
            this.hrm_work_shift = new HashSet<hrm_work_shift>();
            this.hrm_job_interview = new HashSet<hrm_job_interview>();
            this.hrm_location = new HashSet<hrm_location>();
        }
    
        public int emp_number { get; set; }
        public string employee_id { get; set; }
        public string emp_lastname { get; set; }
        public string emp_firstname { get; set; }
        public string emp_middle_name { get; set; }
        public string emp_nick_name { get; set; }
        public Nullable<short> emp_smoker { get; set; }
        public string ethnic_race_code { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public Nullable<int> nation_code { get; set; }
        public Nullable<short> emp_gender { get; set; }
        public string emp_marital_status { get; set; }
        public string emp_ssn_num { get; set; }
        public string emp_sin_num { get; set; }
        public string emp_other_id { get; set; }
        public string emp_dri_lice_num { get; set; }
        public Nullable<System.DateTime> emp_dri_lice_exp_date { get; set; }
        public string emp_military_service { get; set; }
        public Nullable<int> emp_status { get; set; }
        public Nullable<int> job_title_code { get; set; }
        public Nullable<int> eeo_cat_code { get; set; }
        public Nullable<int> work_station { get; set; }
        public string emp_street1 { get; set; }
        public string emp_street2 { get; set; }
        public string city_code { get; set; }
        public string coun_code { get; set; }
        public string provin_code { get; set; }
        public string emp_zipcode { get; set; }
        public string emp_hm_telephone { get; set; }
        public string emp_mobile { get; set; }
        public string emp_work_telephone { get; set; }
        public string emp_work_email { get; set; }
        public string sal_grd_code { get; set; }
        public Nullable<System.DateTime> joined_date { get; set; }
        public string emp_oth_email { get; set; }
        public Nullable<int> termination_id { get; set; }
        public string custom1 { get; set; }
        public string custom2 { get; set; }
        public string custom3 { get; set; }
        public string custom4 { get; set; }
        public string custom5 { get; set; }
        public string custom6 { get; set; }
        public string custom7 { get; set; }
        public string custom8 { get; set; }
        public string custom9 { get; set; }
        public string custom10 { get; set; }
    
        public virtual ICollection<hrm_emp_education> hrm_emp_education { get; set; }
        public virtual ICollection<hrm_emp_license> hrm_emp_license { get; set; }
        public virtual ICollection<hrm_emp_termination> hrm_emp_termination { get; set; }
        public virtual hrm_emp_termination hrm_emp_termination1 { get; set; }
        public virtual hrm_employment_status hrm_employment_status { get; set; }
        public virtual ICollection<hrm_job_candidate> hrm_job_candidate { get; set; }
        public virtual ICollection<hrm_job_candidate_history> hrm_job_candidate_history { get; set; }
        public virtual hrm_job_category hrm_job_category { get; set; }
        public virtual hrm_job_title hrm_job_title { get; set; }
        public virtual ICollection<hrm_job_vacancy> hrm_job_vacancy { get; set; }
        public virtual ICollection<hrm_leave_adjustment> hrm_leave_adjustment { get; set; }
        public virtual ICollection<hrm_leave_comment> hrm_leave_comment { get; set; }
        public virtual ICollection<hrm_leave_entitlement> hrm_leave_entitlement { get; set; }
        public virtual ICollection<hrm_leave_request> hrm_leave_request { get; set; }
        public virtual ICollection<hrm_leave_request_comment> hrm_leave_request_comment { get; set; }
        public virtual hrm_nationality hrm_nationality { get; set; }
        public virtual ICollection<hrm_performance_review> hrm_performance_review { get; set; }
        public virtual ICollection<hrm_performance_track> hrm_performance_track { get; set; }
        public virtual ICollection<hrm_performance_track> hrm_performance_track1 { get; set; }
        public virtual ICollection<hrm_performance_tracker_log> hrm_performance_tracker_log { get; set; }
        public virtual ICollection<hrm_performance_tracker_reviewer> hrm_performance_tracker_reviewer { get; set; }
        public virtual ICollection<hrm_project_admin> hrm_project_admin { get; set; }
        public virtual hrm_subunit hrm_subunit { get; set; }
        public virtual ICollection<hrm_user> hrm_user { get; set; }
        public virtual ICollection<hs_hr_emp_attachment> hs_hr_emp_attachment { get; set; }
        public virtual ICollection<hs_hr_emp_basicsalary> hs_hr_emp_basicsalary { get; set; }
        public virtual ICollection<hs_hr_emp_children> hs_hr_emp_children { get; set; }
        public virtual ICollection<hs_hr_emp_contract_extend> hs_hr_emp_contract_extend { get; set; }
        public virtual ICollection<hs_hr_emp_dependents> hs_hr_emp_dependents { get; set; }
        public virtual ICollection<hs_hr_emp_emergency_contacts> hs_hr_emp_emergency_contacts { get; set; }
        public virtual ICollection<hs_hr_emp_history_of_ealier_pos> hs_hr_emp_history_of_ealier_pos { get; set; }
        public virtual ICollection<hs_hr_emp_language> hs_hr_emp_language { get; set; }
        public virtual ICollection<hs_hr_emp_member_detail> hs_hr_emp_member_detail { get; set; }
        public virtual ICollection<hs_hr_emp_passport> hs_hr_emp_passport { get; set; }
        public virtual hs_hr_emp_picture hs_hr_emp_picture { get; set; }
        public virtual ICollection<hs_hr_emp_reportto> hs_hr_emp_reportto { get; set; }
        public virtual ICollection<hs_hr_emp_reportto> hs_hr_emp_reportto1 { get; set; }
        public virtual hs_hr_emp_us_tax hs_hr_emp_us_tax { get; set; }
        public virtual ICollection<hs_hr_emp_work_experience> hs_hr_emp_work_experience { get; set; }
        public virtual ICollection<hs_hr_emp_skill> hs_hr_emp_skill { get; set; }
        public virtual ICollection<hrm_work_shift> hrm_work_shift { get; set; }
        public virtual ICollection<hrm_job_interview> hrm_job_interview { get; set; }
        public virtual ICollection<hrm_location> hrm_location { get; set; }
    }
}
