//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_language
    {
        public int emp_number { get; set; }
        public int lang_id { get; set; }
        public short fluency { get; set; }
        public Nullable<short> competency { get; set; }
        public string comments { get; set; }
    
        public virtual hrm_language hrm_language { get; set; }
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
