//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_picture
    {
        public int emp_number { get; set; }
        public byte[] epic_picture { get; set; }
        public string epic_filename { get; set; }
        public string epic_type { get; set; }
        public string epic_file_size { get; set; }
        public string epic_file_width { get; set; }
        public string epic_file_height { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
