//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_us_tax
    {
        public int emp_number { get; set; }
        public string tax_federal_status { get; set; }
        public Nullable<int> tax_federal_exceptions { get; set; }
        public string tax_state { get; set; }
        public string tax_state_status { get; set; }
        public Nullable<int> tax_state_exceptions { get; set; }
        public string tax_unemp_state { get; set; }
        public string tax_work_state { get; set; }
    
        public virtual hs_hr_employee hs_hr_employee { get; set; }
    }
}
