//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM.Spar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hs_hr_emp_directdebit
    {
        public int id { get; set; }
        public int salary_id { get; set; }
        public int dd_routing_num { get; set; }
        public string dd_account { get; set; }
        public decimal dd_amount { get; set; }
        public string dd_account_type { get; set; }
        public string dd_transaction_type { get; set; }
    
        public virtual hs_hr_emp_basicsalary hs_hr_emp_basicsalary { get; set; }
    }
}
